# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /net/hel/export/9/student/v/vbruder/ProjectCPP/Asteroids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /net/hel/export/9/student/v/vbruder/ProjectCPP/Asteroids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /net/hel/export/9/student/v/vbruder/ProjectCPP/Asteroids/CMakeFiles /net/hel/export/9/student/v/vbruder/ProjectCPP/Asteroids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /net/hel/export/9/student/v/vbruder/ProjectCPP/Asteroids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named viewer

# Build rule for target.
viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viewer
.PHONY : viewer

# fast build rule for target.
viewer/fast:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/build
.PHONY : viewer/fast

#=============================================================================
# Target rules for targets named c3dsreader

# Build rule for target.
c3dsreader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c3dsreader
.PHONY : c3dsreader

# fast build rule for target.
c3dsreader/fast:
	$(MAKE) -f ext/load3ds/CMakeFiles/c3dsreader.dir/build.make ext/load3ds/CMakeFiles/c3dsreader.dir/build
.PHONY : c3dsreader/fast

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/Main.cpp.s
.PHONY : Main.cpp.s

control/Logic.o: control/Logic.cpp.o
.PHONY : control/Logic.o

# target to build an object file
control/Logic.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/control/Logic.cpp.o
.PHONY : control/Logic.cpp.o

control/Logic.i: control/Logic.cpp.i
.PHONY : control/Logic.i

# target to preprocess a source file
control/Logic.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/control/Logic.cpp.i
.PHONY : control/Logic.cpp.i

control/Logic.s: control/Logic.cpp.s
.PHONY : control/Logic.s

# target to generate assembly for a file
control/Logic.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/control/Logic.cpp.s
.PHONY : control/Logic.cpp.s

io/HighScore.o: io/HighScore.cpp.o
.PHONY : io/HighScore.o

# target to build an object file
io/HighScore.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/HighScore.cpp.o
.PHONY : io/HighScore.cpp.o

io/HighScore.i: io/HighScore.cpp.i
.PHONY : io/HighScore.i

# target to preprocess a source file
io/HighScore.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/HighScore.cpp.i
.PHONY : io/HighScore.cpp.i

io/HighScore.s: io/HighScore.cpp.s
.PHONY : io/HighScore.s

# target to generate assembly for a file
io/HighScore.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/HighScore.cpp.s
.PHONY : io/HighScore.cpp.s

io/LevelMaker.o: io/LevelMaker.cpp.o
.PHONY : io/LevelMaker.o

# target to build an object file
io/LevelMaker.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelMaker.cpp.o
.PHONY : io/LevelMaker.cpp.o

io/LevelMaker.i: io/LevelMaker.cpp.i
.PHONY : io/LevelMaker.i

# target to preprocess a source file
io/LevelMaker.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelMaker.cpp.i
.PHONY : io/LevelMaker.cpp.i

io/LevelMaker.s: io/LevelMaker.cpp.s
.PHONY : io/LevelMaker.s

# target to generate assembly for a file
io/LevelMaker.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelMaker.cpp.s
.PHONY : io/LevelMaker.cpp.s

io/LevelReader.o: io/LevelReader.cpp.o
.PHONY : io/LevelReader.o

# target to build an object file
io/LevelReader.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelReader.cpp.o
.PHONY : io/LevelReader.cpp.o

io/LevelReader.i: io/LevelReader.cpp.i
.PHONY : io/LevelReader.i

# target to preprocess a source file
io/LevelReader.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelReader.cpp.i
.PHONY : io/LevelReader.cpp.i

io/LevelReader.s: io/LevelReader.cpp.s
.PHONY : io/LevelReader.s

# target to generate assembly for a file
io/LevelReader.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/LevelReader.cpp.s
.PHONY : io/LevelReader.cpp.s

io/PLYTraits.o: io/PLYTraits.cpp.o
.PHONY : io/PLYTraits.o

# target to build an object file
io/PLYTraits.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/PLYTraits.cpp.o
.PHONY : io/PLYTraits.cpp.o

io/PLYTraits.i: io/PLYTraits.cpp.i
.PHONY : io/PLYTraits.i

# target to preprocess a source file
io/PLYTraits.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/PLYTraits.cpp.i
.PHONY : io/PLYTraits.cpp.i

io/PLYTraits.s: io/PLYTraits.cpp.s
.PHONY : io/PLYTraits.s

# target to generate assembly for a file
io/PLYTraits.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/PLYTraits.cpp.s
.PHONY : io/PLYTraits.cpp.s

io/Read3DS.o: io/Read3DS.cpp.o
.PHONY : io/Read3DS.o

# target to build an object file
io/Read3DS.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/Read3DS.cpp.o
.PHONY : io/Read3DS.cpp.o

io/Read3DS.i: io/Read3DS.cpp.i
.PHONY : io/Read3DS.i

# target to preprocess a source file
io/Read3DS.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/Read3DS.cpp.i
.PHONY : io/Read3DS.cpp.i

io/Read3DS.s: io/Read3DS.cpp.s
.PHONY : io/Read3DS.s

# target to generate assembly for a file
io/Read3DS.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/Read3DS.cpp.s
.PHONY : io/Read3DS.cpp.s

io/ReadPLY.o: io/ReadPLY.cpp.o
.PHONY : io/ReadPLY.o

# target to build an object file
io/ReadPLY.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPLY.cpp.o
.PHONY : io/ReadPLY.cpp.o

io/ReadPLY.i: io/ReadPLY.cpp.i
.PHONY : io/ReadPLY.i

# target to preprocess a source file
io/ReadPLY.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPLY.cpp.i
.PHONY : io/ReadPLY.cpp.i

io/ReadPLY.s: io/ReadPLY.cpp.s
.PHONY : io/ReadPLY.s

# target to generate assembly for a file
io/ReadPLY.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPLY.cpp.s
.PHONY : io/ReadPLY.cpp.s

io/ReadPPM.o: io/ReadPPM.cpp.o
.PHONY : io/ReadPPM.o

# target to build an object file
io/ReadPPM.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPPM.cpp.o
.PHONY : io/ReadPPM.cpp.o

io/ReadPPM.i: io/ReadPPM.cpp.i
.PHONY : io/ReadPPM.i

# target to preprocess a source file
io/ReadPPM.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPPM.cpp.i
.PHONY : io/ReadPPM.cpp.i

io/ReadPPM.s: io/ReadPPM.cpp.s
.PHONY : io/ReadPPM.s

# target to generate assembly for a file
io/ReadPPM.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadPPM.cpp.s
.PHONY : io/ReadPPM.cpp.s

io/ReadTGA.o: io/ReadTGA.cpp.o
.PHONY : io/ReadTGA.o

# target to build an object file
io/ReadTGA.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadTGA.cpp.o
.PHONY : io/ReadTGA.cpp.o

io/ReadTGA.i: io/ReadTGA.cpp.i
.PHONY : io/ReadTGA.i

# target to preprocess a source file
io/ReadTGA.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadTGA.cpp.i
.PHONY : io/ReadTGA.cpp.i

io/ReadTGA.s: io/ReadTGA.cpp.s
.PHONY : io/ReadTGA.s

# target to generate assembly for a file
io/ReadTGA.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/ReadTGA.cpp.s
.PHONY : io/ReadTGA.cpp.s

io/SoundOutput.o: io/SoundOutput.cpp.o
.PHONY : io/SoundOutput.o

# target to build an object file
io/SoundOutput.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/SoundOutput.cpp.o
.PHONY : io/SoundOutput.cpp.o

io/SoundOutput.i: io/SoundOutput.cpp.i
.PHONY : io/SoundOutput.i

# target to preprocess a source file
io/SoundOutput.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/SoundOutput.cpp.i
.PHONY : io/SoundOutput.cpp.i

io/SoundOutput.s: io/SoundOutput.cpp.s
.PHONY : io/SoundOutput.s

# target to generate assembly for a file
io/SoundOutput.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/SoundOutput.cpp.s
.PHONY : io/SoundOutput.cpp.s

io/TextureFactory.o: io/TextureFactory.cpp.o
.PHONY : io/TextureFactory.o

# target to build an object file
io/TextureFactory.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TextureFactory.cpp.o
.PHONY : io/TextureFactory.cpp.o

io/TextureFactory.i: io/TextureFactory.cpp.i
.PHONY : io/TextureFactory.i

# target to preprocess a source file
io/TextureFactory.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TextureFactory.cpp.i
.PHONY : io/TextureFactory.cpp.i

io/TextureFactory.s: io/TextureFactory.cpp.s
.PHONY : io/TextureFactory.s

# target to generate assembly for a file
io/TextureFactory.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TextureFactory.cpp.s
.PHONY : io/TextureFactory.cpp.s

io/TriangleMeshFactory.o: io/TriangleMeshFactory.cpp.o
.PHONY : io/TriangleMeshFactory.o

# target to build an object file
io/TriangleMeshFactory.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TriangleMeshFactory.cpp.o
.PHONY : io/TriangleMeshFactory.cpp.o

io/TriangleMeshFactory.i: io/TriangleMeshFactory.cpp.i
.PHONY : io/TriangleMeshFactory.i

# target to preprocess a source file
io/TriangleMeshFactory.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TriangleMeshFactory.cpp.i
.PHONY : io/TriangleMeshFactory.cpp.i

io/TriangleMeshFactory.s: io/TriangleMeshFactory.cpp.s
.PHONY : io/TriangleMeshFactory.s

# target to generate assembly for a file
io/TriangleMeshFactory.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/io/TriangleMeshFactory.cpp.s
.PHONY : io/TriangleMeshFactory.cpp.s

moc_MainWindow.o: moc_MainWindow.cxx.o
.PHONY : moc_MainWindow.o

# target to build an object file
moc_MainWindow.cxx.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_MainWindow.cxx.o
.PHONY : moc_MainWindow.cxx.o

moc_MainWindow.i: moc_MainWindow.cxx.i
.PHONY : moc_MainWindow.i

# target to preprocess a source file
moc_MainWindow.cxx.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_MainWindow.cxx.i
.PHONY : moc_MainWindow.cxx.i

moc_MainWindow.s: moc_MainWindow.cxx.s
.PHONY : moc_MainWindow.s

# target to generate assembly for a file
moc_MainWindow.cxx.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_MainWindow.cxx.s
.PHONY : moc_MainWindow.cxx.s

moc_Menu.o: moc_Menu.cxx.o
.PHONY : moc_Menu.o

# target to build an object file
moc_Menu.cxx.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_Menu.cxx.o
.PHONY : moc_Menu.cxx.o

moc_Menu.i: moc_Menu.cxx.i
.PHONY : moc_Menu.i

# target to preprocess a source file
moc_Menu.cxx.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_Menu.cxx.i
.PHONY : moc_Menu.cxx.i

moc_Menu.s: moc_Menu.cxx.s
.PHONY : moc_Menu.s

# target to generate assembly for a file
moc_Menu.cxx.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_Menu.cxx.s
.PHONY : moc_Menu.cxx.s

moc_RenderFrame.o: moc_RenderFrame.cxx.o
.PHONY : moc_RenderFrame.o

# target to build an object file
moc_RenderFrame.cxx.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_RenderFrame.cxx.o
.PHONY : moc_RenderFrame.cxx.o

moc_RenderFrame.i: moc_RenderFrame.cxx.i
.PHONY : moc_RenderFrame.i

# target to preprocess a source file
moc_RenderFrame.cxx.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_RenderFrame.cxx.i
.PHONY : moc_RenderFrame.cxx.i

moc_RenderFrame.s: moc_RenderFrame.cxx.s
.PHONY : moc_RenderFrame.s

# target to generate assembly for a file
moc_RenderFrame.cxx.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/moc_RenderFrame.cxx.s
.PHONY : moc_RenderFrame.cxx.s

rendering/Asteroid.o: rendering/Asteroid.cpp.o
.PHONY : rendering/Asteroid.o

# target to build an object file
rendering/Asteroid.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Asteroid.cpp.o
.PHONY : rendering/Asteroid.cpp.o

rendering/Asteroid.i: rendering/Asteroid.cpp.i
.PHONY : rendering/Asteroid.i

# target to preprocess a source file
rendering/Asteroid.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Asteroid.cpp.i
.PHONY : rendering/Asteroid.cpp.i

rendering/Asteroid.s: rendering/Asteroid.cpp.s
.PHONY : rendering/Asteroid.s

# target to generate assembly for a file
rendering/Asteroid.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Asteroid.cpp.s
.PHONY : rendering/Asteroid.cpp.s

rendering/Body.o: rendering/Body.cpp.o
.PHONY : rendering/Body.o

# target to build an object file
rendering/Body.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Body.cpp.o
.PHONY : rendering/Body.cpp.o

rendering/Body.i: rendering/Body.cpp.i
.PHONY : rendering/Body.i

# target to preprocess a source file
rendering/Body.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Body.cpp.i
.PHONY : rendering/Body.cpp.i

rendering/Body.s: rendering/Body.cpp.s
.PHONY : rendering/Body.s

# target to generate assembly for a file
rendering/Body.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Body.cpp.s
.PHONY : rendering/Body.cpp.s

rendering/BodySet.o: rendering/BodySet.cpp.o
.PHONY : rendering/BodySet.o

# target to build an object file
rendering/BodySet.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/BodySet.cpp.o
.PHONY : rendering/BodySet.cpp.o

rendering/BodySet.i: rendering/BodySet.cpp.i
.PHONY : rendering/BodySet.i

# target to preprocess a source file
rendering/BodySet.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/BodySet.cpp.i
.PHONY : rendering/BodySet.cpp.i

rendering/BodySet.s: rendering/BodySet.cpp.s
.PHONY : rendering/BodySet.s

# target to generate assembly for a file
rendering/BodySet.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/BodySet.cpp.s
.PHONY : rendering/BodySet.cpp.s

rendering/Bullet.o: rendering/Bullet.cpp.o
.PHONY : rendering/Bullet.o

# target to build an object file
rendering/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Bullet.cpp.o
.PHONY : rendering/Bullet.cpp.o

rendering/Bullet.i: rendering/Bullet.cpp.i
.PHONY : rendering/Bullet.i

# target to preprocess a source file
rendering/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Bullet.cpp.i
.PHONY : rendering/Bullet.cpp.i

rendering/Bullet.s: rendering/Bullet.cpp.s
.PHONY : rendering/Bullet.s

# target to generate assembly for a file
rendering/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Bullet.cpp.s
.PHONY : rendering/Bullet.cpp.s

rendering/Fighter.o: rendering/Fighter.cpp.o
.PHONY : rendering/Fighter.o

# target to build an object file
rendering/Fighter.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Fighter.cpp.o
.PHONY : rendering/Fighter.cpp.o

rendering/Fighter.i: rendering/Fighter.cpp.i
.PHONY : rendering/Fighter.i

# target to preprocess a source file
rendering/Fighter.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Fighter.cpp.i
.PHONY : rendering/Fighter.cpp.i

rendering/Fighter.s: rendering/Fighter.cpp.s
.PHONY : rendering/Fighter.s

# target to generate assembly for a file
rendering/Fighter.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Fighter.cpp.s
.PHONY : rendering/Fighter.cpp.s

rendering/Hud.o: rendering/Hud.cpp.o
.PHONY : rendering/Hud.o

# target to build an object file
rendering/Hud.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Hud.cpp.o
.PHONY : rendering/Hud.cpp.o

rendering/Hud.i: rendering/Hud.cpp.i
.PHONY : rendering/Hud.i

# target to preprocess a source file
rendering/Hud.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Hud.cpp.i
.PHONY : rendering/Hud.cpp.i

rendering/Hud.s: rendering/Hud.cpp.s
.PHONY : rendering/Hud.s

# target to generate assembly for a file
rendering/Hud.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Hud.cpp.s
.PHONY : rendering/Hud.cpp.s

rendering/Laser.o: rendering/Laser.cpp.o
.PHONY : rendering/Laser.o

# target to build an object file
rendering/Laser.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Laser.cpp.o
.PHONY : rendering/Laser.cpp.o

rendering/Laser.i: rendering/Laser.cpp.i
.PHONY : rendering/Laser.i

# target to preprocess a source file
rendering/Laser.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Laser.cpp.i
.PHONY : rendering/Laser.cpp.i

rendering/Laser.s: rendering/Laser.cpp.s
.PHONY : rendering/Laser.s

# target to generate assembly for a file
rendering/Laser.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Laser.cpp.s
.PHONY : rendering/Laser.cpp.s

rendering/Menu.o: rendering/Menu.cpp.o
.PHONY : rendering/Menu.o

# target to build an object file
rendering/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Menu.cpp.o
.PHONY : rendering/Menu.cpp.o

rendering/Menu.i: rendering/Menu.cpp.i
.PHONY : rendering/Menu.i

# target to preprocess a source file
rendering/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Menu.cpp.i
.PHONY : rendering/Menu.cpp.i

rendering/Menu.s: rendering/Menu.cpp.s
.PHONY : rendering/Menu.s

# target to generate assembly for a file
rendering/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Menu.cpp.s
.PHONY : rendering/Menu.cpp.s

rendering/MenuButton.o: rendering/MenuButton.cpp.o
.PHONY : rendering/MenuButton.o

# target to build an object file
rendering/MenuButton.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuButton.cpp.o
.PHONY : rendering/MenuButton.cpp.o

rendering/MenuButton.i: rendering/MenuButton.cpp.i
.PHONY : rendering/MenuButton.i

# target to preprocess a source file
rendering/MenuButton.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuButton.cpp.i
.PHONY : rendering/MenuButton.cpp.i

rendering/MenuButton.s: rendering/MenuButton.cpp.s
.PHONY : rendering/MenuButton.s

# target to generate assembly for a file
rendering/MenuButton.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuButton.cpp.s
.PHONY : rendering/MenuButton.cpp.s

rendering/MenuElement.o: rendering/MenuElement.cpp.o
.PHONY : rendering/MenuElement.o

# target to build an object file
rendering/MenuElement.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuElement.cpp.o
.PHONY : rendering/MenuElement.cpp.o

rendering/MenuElement.i: rendering/MenuElement.cpp.i
.PHONY : rendering/MenuElement.i

# target to preprocess a source file
rendering/MenuElement.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuElement.cpp.i
.PHONY : rendering/MenuElement.cpp.i

rendering/MenuElement.s: rendering/MenuElement.cpp.s
.PHONY : rendering/MenuElement.s

# target to generate assembly for a file
rendering/MenuElement.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuElement.cpp.s
.PHONY : rendering/MenuElement.cpp.s

rendering/MenuSet.o: rendering/MenuSet.cpp.o
.PHONY : rendering/MenuSet.o

# target to build an object file
rendering/MenuSet.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuSet.cpp.o
.PHONY : rendering/MenuSet.cpp.o

rendering/MenuSet.i: rendering/MenuSet.cpp.i
.PHONY : rendering/MenuSet.i

# target to preprocess a source file
rendering/MenuSet.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuSet.cpp.i
.PHONY : rendering/MenuSet.cpp.i

rendering/MenuSet.s: rendering/MenuSet.cpp.s
.PHONY : rendering/MenuSet.s

# target to generate assembly for a file
rendering/MenuSet.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/MenuSet.cpp.s
.PHONY : rendering/MenuSet.cpp.s

rendering/Particle.o: rendering/Particle.cpp.o
.PHONY : rendering/Particle.o

# target to build an object file
rendering/Particle.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Particle.cpp.o
.PHONY : rendering/Particle.cpp.o

rendering/Particle.i: rendering/Particle.cpp.i
.PHONY : rendering/Particle.i

# target to preprocess a source file
rendering/Particle.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Particle.cpp.i
.PHONY : rendering/Particle.cpp.i

rendering/Particle.s: rendering/Particle.cpp.s
.PHONY : rendering/Particle.s

# target to generate assembly for a file
rendering/Particle.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Particle.cpp.s
.PHONY : rendering/Particle.cpp.s

rendering/Plasma.o: rendering/Plasma.cpp.o
.PHONY : rendering/Plasma.o

# target to build an object file
rendering/Plasma.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Plasma.cpp.o
.PHONY : rendering/Plasma.cpp.o

rendering/Plasma.i: rendering/Plasma.cpp.i
.PHONY : rendering/Plasma.i

# target to preprocess a source file
rendering/Plasma.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Plasma.cpp.i
.PHONY : rendering/Plasma.cpp.i

rendering/Plasma.s: rendering/Plasma.cpp.s
.PHONY : rendering/Plasma.s

# target to generate assembly for a file
rendering/Plasma.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Plasma.cpp.s
.PHONY : rendering/Plasma.cpp.s

rendering/PowerUp.o: rendering/PowerUp.cpp.o
.PHONY : rendering/PowerUp.o

# target to build an object file
rendering/PowerUp.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/PowerUp.cpp.o
.PHONY : rendering/PowerUp.cpp.o

rendering/PowerUp.i: rendering/PowerUp.cpp.i
.PHONY : rendering/PowerUp.i

# target to preprocess a source file
rendering/PowerUp.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/PowerUp.cpp.i
.PHONY : rendering/PowerUp.cpp.i

rendering/PowerUp.s: rendering/PowerUp.cpp.s
.PHONY : rendering/PowerUp.s

# target to generate assembly for a file
rendering/PowerUp.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/PowerUp.cpp.s
.PHONY : rendering/PowerUp.cpp.s

rendering/Shield.o: rendering/Shield.cpp.o
.PHONY : rendering/Shield.o

# target to build an object file
rendering/Shield.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Shield.cpp.o
.PHONY : rendering/Shield.cpp.o

rendering/Shield.i: rendering/Shield.cpp.i
.PHONY : rendering/Shield.i

# target to preprocess a source file
rendering/Shield.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Shield.cpp.i
.PHONY : rendering/Shield.cpp.i

rendering/Shield.s: rendering/Shield.cpp.s
.PHONY : rendering/Shield.s

# target to generate assembly for a file
rendering/Shield.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Shield.cpp.s
.PHONY : rendering/Shield.cpp.s

rendering/Skybox.o: rendering/Skybox.cpp.o
.PHONY : rendering/Skybox.o

# target to build an object file
rendering/Skybox.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Skybox.cpp.o
.PHONY : rendering/Skybox.cpp.o

rendering/Skybox.i: rendering/Skybox.cpp.i
.PHONY : rendering/Skybox.i

# target to preprocess a source file
rendering/Skybox.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Skybox.cpp.i
.PHONY : rendering/Skybox.cpp.i

rendering/Skybox.s: rendering/Skybox.cpp.s
.PHONY : rendering/Skybox.s

# target to generate assembly for a file
rendering/Skybox.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Skybox.cpp.s
.PHONY : rendering/Skybox.cpp.s

rendering/Texture.o: rendering/Texture.cpp.o
.PHONY : rendering/Texture.o

# target to build an object file
rendering/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Texture.cpp.o
.PHONY : rendering/Texture.cpp.o

rendering/Texture.i: rendering/Texture.cpp.i
.PHONY : rendering/Texture.i

# target to preprocess a source file
rendering/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Texture.cpp.i
.PHONY : rendering/Texture.cpp.i

rendering/Texture.s: rendering/Texture.cpp.s
.PHONY : rendering/Texture.s

# target to generate assembly for a file
rendering/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Texture.cpp.s
.PHONY : rendering/Texture.cpp.s

rendering/TexturedMesh.o: rendering/TexturedMesh.cpp.o
.PHONY : rendering/TexturedMesh.o

# target to build an object file
rendering/TexturedMesh.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TexturedMesh.cpp.o
.PHONY : rendering/TexturedMesh.cpp.o

rendering/TexturedMesh.i: rendering/TexturedMesh.cpp.i
.PHONY : rendering/TexturedMesh.i

# target to preprocess a source file
rendering/TexturedMesh.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TexturedMesh.cpp.i
.PHONY : rendering/TexturedMesh.cpp.i

rendering/TexturedMesh.s: rendering/TexturedMesh.cpp.s
.PHONY : rendering/TexturedMesh.s

# target to generate assembly for a file
rendering/TexturedMesh.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TexturedMesh.cpp.s
.PHONY : rendering/TexturedMesh.cpp.s

rendering/Transformable.o: rendering/Transformable.cpp.o
.PHONY : rendering/Transformable.o

# target to build an object file
rendering/Transformable.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Transformable.cpp.o
.PHONY : rendering/Transformable.cpp.o

rendering/Transformable.i: rendering/Transformable.cpp.i
.PHONY : rendering/Transformable.i

# target to preprocess a source file
rendering/Transformable.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Transformable.cpp.i
.PHONY : rendering/Transformable.cpp.i

rendering/Transformable.s: rendering/Transformable.cpp.s
.PHONY : rendering/Transformable.s

# target to generate assembly for a file
rendering/Transformable.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Transformable.cpp.s
.PHONY : rendering/Transformable.cpp.s

rendering/TriangleMesh.o: rendering/TriangleMesh.cpp.o
.PHONY : rendering/TriangleMesh.o

# target to build an object file
rendering/TriangleMesh.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TriangleMesh.cpp.o
.PHONY : rendering/TriangleMesh.cpp.o

rendering/TriangleMesh.i: rendering/TriangleMesh.cpp.i
.PHONY : rendering/TriangleMesh.i

# target to preprocess a source file
rendering/TriangleMesh.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TriangleMesh.cpp.i
.PHONY : rendering/TriangleMesh.cpp.i

rendering/TriangleMesh.s: rendering/TriangleMesh.cpp.s
.PHONY : rendering/TriangleMesh.s

# target to generate assembly for a file
rendering/TriangleMesh.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/TriangleMesh.cpp.s
.PHONY : rendering/TriangleMesh.cpp.s

rendering/Weapon.o: rendering/Weapon.cpp.o
.PHONY : rendering/Weapon.o

# target to build an object file
rendering/Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Weapon.cpp.o
.PHONY : rendering/Weapon.cpp.o

rendering/Weapon.i: rendering/Weapon.cpp.i
.PHONY : rendering/Weapon.i

# target to preprocess a source file
rendering/Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Weapon.cpp.i
.PHONY : rendering/Weapon.cpp.i

rendering/Weapon.s: rendering/Weapon.cpp.s
.PHONY : rendering/Weapon.s

# target to generate assembly for a file
rendering/Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/rendering/Weapon.cpp.s
.PHONY : rendering/Weapon.cpp.s

view/Camera.o: view/Camera.cpp.o
.PHONY : view/Camera.o

# target to build an object file
view/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/Camera.cpp.o
.PHONY : view/Camera.cpp.o

view/Camera.i: view/Camera.cpp.i
.PHONY : view/Camera.i

# target to preprocess a source file
view/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/Camera.cpp.i
.PHONY : view/Camera.cpp.i

view/Camera.s: view/Camera.cpp.s
.PHONY : view/Camera.s

# target to generate assembly for a file
view/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/Camera.cpp.s
.PHONY : view/Camera.cpp.s

view/MainWindow.o: view/MainWindow.cpp.o
.PHONY : view/MainWindow.o

# target to build an object file
view/MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/MainWindow.cpp.o
.PHONY : view/MainWindow.cpp.o

view/MainWindow.i: view/MainWindow.cpp.i
.PHONY : view/MainWindow.i

# target to preprocess a source file
view/MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/MainWindow.cpp.i
.PHONY : view/MainWindow.cpp.i

view/MainWindow.s: view/MainWindow.cpp.s
.PHONY : view/MainWindow.s

# target to generate assembly for a file
view/MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/MainWindow.cpp.s
.PHONY : view/MainWindow.cpp.s

view/RenderFrame.o: view/RenderFrame.cpp.o
.PHONY : view/RenderFrame.o

# target to build an object file
view/RenderFrame.cpp.o:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/RenderFrame.cpp.o
.PHONY : view/RenderFrame.cpp.o

view/RenderFrame.i: view/RenderFrame.cpp.i
.PHONY : view/RenderFrame.i

# target to preprocess a source file
view/RenderFrame.cpp.i:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/RenderFrame.cpp.i
.PHONY : view/RenderFrame.cpp.i

view/RenderFrame.s: view/RenderFrame.cpp.s
.PHONY : view/RenderFrame.s

# target to generate assembly for a file
view/RenderFrame.cpp.s:
	$(MAKE) -f CMakeFiles/viewer.dir/build.make CMakeFiles/viewer.dir/view/RenderFrame.cpp.s
.PHONY : view/RenderFrame.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... viewer"
	@echo "... c3dsreader"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... control/Logic.o"
	@echo "... control/Logic.i"
	@echo "... control/Logic.s"
	@echo "... io/HighScore.o"
	@echo "... io/HighScore.i"
	@echo "... io/HighScore.s"
	@echo "... io/LevelMaker.o"
	@echo "... io/LevelMaker.i"
	@echo "... io/LevelMaker.s"
	@echo "... io/LevelReader.o"
	@echo "... io/LevelReader.i"
	@echo "... io/LevelReader.s"
	@echo "... io/PLYTraits.o"
	@echo "... io/PLYTraits.i"
	@echo "... io/PLYTraits.s"
	@echo "... io/Read3DS.o"
	@echo "... io/Read3DS.i"
	@echo "... io/Read3DS.s"
	@echo "... io/ReadPLY.o"
	@echo "... io/ReadPLY.i"
	@echo "... io/ReadPLY.s"
	@echo "... io/ReadPPM.o"
	@echo "... io/ReadPPM.i"
	@echo "... io/ReadPPM.s"
	@echo "... io/ReadTGA.o"
	@echo "... io/ReadTGA.i"
	@echo "... io/ReadTGA.s"
	@echo "... io/SoundOutput.o"
	@echo "... io/SoundOutput.i"
	@echo "... io/SoundOutput.s"
	@echo "... io/TextureFactory.o"
	@echo "... io/TextureFactory.i"
	@echo "... io/TextureFactory.s"
	@echo "... io/TriangleMeshFactory.o"
	@echo "... io/TriangleMeshFactory.i"
	@echo "... io/TriangleMeshFactory.s"
	@echo "... moc_MainWindow.o"
	@echo "... moc_MainWindow.i"
	@echo "... moc_MainWindow.s"
	@echo "... moc_Menu.o"
	@echo "... moc_Menu.i"
	@echo "... moc_Menu.s"
	@echo "... moc_RenderFrame.o"
	@echo "... moc_RenderFrame.i"
	@echo "... moc_RenderFrame.s"
	@echo "... rendering/Asteroid.o"
	@echo "... rendering/Asteroid.i"
	@echo "... rendering/Asteroid.s"
	@echo "... rendering/Body.o"
	@echo "... rendering/Body.i"
	@echo "... rendering/Body.s"
	@echo "... rendering/BodySet.o"
	@echo "... rendering/BodySet.i"
	@echo "... rendering/BodySet.s"
	@echo "... rendering/Bullet.o"
	@echo "... rendering/Bullet.i"
	@echo "... rendering/Bullet.s"
	@echo "... rendering/Fighter.o"
	@echo "... rendering/Fighter.i"
	@echo "... rendering/Fighter.s"
	@echo "... rendering/Hud.o"
	@echo "... rendering/Hud.i"
	@echo "... rendering/Hud.s"
	@echo "... rendering/Laser.o"
	@echo "... rendering/Laser.i"
	@echo "... rendering/Laser.s"
	@echo "... rendering/Menu.o"
	@echo "... rendering/Menu.i"
	@echo "... rendering/Menu.s"
	@echo "... rendering/MenuButton.o"
	@echo "... rendering/MenuButton.i"
	@echo "... rendering/MenuButton.s"
	@echo "... rendering/MenuElement.o"
	@echo "... rendering/MenuElement.i"
	@echo "... rendering/MenuElement.s"
	@echo "... rendering/MenuSet.o"
	@echo "... rendering/MenuSet.i"
	@echo "... rendering/MenuSet.s"
	@echo "... rendering/Particle.o"
	@echo "... rendering/Particle.i"
	@echo "... rendering/Particle.s"
	@echo "... rendering/Plasma.o"
	@echo "... rendering/Plasma.i"
	@echo "... rendering/Plasma.s"
	@echo "... rendering/PowerUp.o"
	@echo "... rendering/PowerUp.i"
	@echo "... rendering/PowerUp.s"
	@echo "... rendering/Shield.o"
	@echo "... rendering/Shield.i"
	@echo "... rendering/Shield.s"
	@echo "... rendering/Skybox.o"
	@echo "... rendering/Skybox.i"
	@echo "... rendering/Skybox.s"
	@echo "... rendering/Texture.o"
	@echo "... rendering/Texture.i"
	@echo "... rendering/Texture.s"
	@echo "... rendering/TexturedMesh.o"
	@echo "... rendering/TexturedMesh.i"
	@echo "... rendering/TexturedMesh.s"
	@echo "... rendering/Transformable.o"
	@echo "... rendering/Transformable.i"
	@echo "... rendering/Transformable.s"
	@echo "... rendering/TriangleMesh.o"
	@echo "... rendering/TriangleMesh.i"
	@echo "... rendering/TriangleMesh.s"
	@echo "... rendering/Weapon.o"
	@echo "... rendering/Weapon.i"
	@echo "... rendering/Weapon.s"
	@echo "... view/Camera.o"
	@echo "... view/Camera.i"
	@echo "... view/Camera.s"
	@echo "... view/MainWindow.o"
	@echo "... view/MainWindow.i"
	@echo "... view/MainWindow.s"
	@echo "... view/RenderFrame.o"
	@echo "... view/RenderFrame.i"
	@echo "... view/RenderFrame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

